"""add gallery_photos table

Revision ID: 2e2a55f15180
Revises: 
Create Date: 2026-03-01 11:24:45.125992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2a55f15180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('caption_fr', sa.String(length=300), nullable=True),
    sa.Column('caption_ar', sa.String(length=300), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    op.drop_table('registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_complet', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('chambre_double', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('avec_enfants', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pptx_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='registration_pkey')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('title_ar', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price_night', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('program_pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_pkey')
    )
    op.drop_table('gallery_photos')
    # ### end Alembic commands ###
